djangoProject/app_users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from django.contrib.auth import views as auth_views
from app_users.views import (
    LoginView, RegistrationView, AccountView, ProfileView,
    ProductHistoryView, OrderHistoryView, OrderUserDetailView
)

urlpatterns = [
    path('user/<slug:slug>/', AccountView.as_view(), name='account'),
    path('user/<slug:slug>/edit/', ProfileView.as_view(),
         name='account_update'),
    path('user/<slug:slug>/history_products/', ProductHistoryView.as_view(),
         name='history_products'),
    path('user/<slug:slug>/history_orders/', OrderHistoryView.as_view(),
         name='history_orders'),
    path('user/<slug:slug>/history_orders/<int:pk>/',
         OrderUserDetailView.as_view(), name='user_order_detail'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), {'next_page': '/'}, name='logout'),
    path('registration/', RegistrationView.as_view(), name='registration'),
    path(
        'password_change/done/',
        auth_views.PasswordChangeDoneView.as_view(
            template_name='app_users/password_change_done.html'),
        name='password_change_done'
    ),
    path(
        'password_change/',
        auth_views.PasswordChangeView.as_view(
            template_name='app_users/password_change.html'),
        name='password_change'
    ),
    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='app_users/password_reset_done.html'),
         name='password_reset_done'),
    path(
        'password_reset/',
        auth_views.PasswordResetView.as_view(
            template_name='app_users/password_reset_form.html'
        ),
        name='password_reset'
    ),
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='app_users/password_reset_complete.html'),
        name='password_reset_complete'
    ),
]

djangoProject/djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# import debug_toolbar

from app_marketplace.views import ClearCacheAdminView

urlpatterns = [
    path('admin/clearcache/', ClearCacheAdminView.as_view(),
         name="clearcache_admin"),
    path('admin/', admin.site.urls),
    path('account/', include('app_users.urls')),
    path('', include('app_marketplace.urls')),
    path('', include('pay_api.urls')),
    # path('__debug__/', include(debug_toolbar.urls)),
    path('i18n', include('django.conf.urls.i18n')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

djangoProject/pay_api/urls.py
from django.urls import path
from .views import PaymentsAPIView

urlpatterns = [
    path('pay/', PaymentsAPIView.as_view(), name='payments_api')
]

djangoProject/app_users/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import FileExtensionValidator
from django.db import models
from django.core.exceptions import ValidationError
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


def get_default_avatar():
    """Функция возврата пути расположения изображения профиля по умолчанию."""
    return "default_avatar/default_avatar.jpg"


def validate_size_image(file_obj):
    """Функция проверки размера файла."""
    megabyte_limit = 2
    if file_obj.size > megabyte_limit * 1024 * 1024:
        raise ValidationError(
            f'{_("Максимальный размер файла")} {megabyte_limit} MB'
        )


class User(AbstractUser):
    """Модель пользователя."""
    avatar = models.ImageField(
        upload_to='User_avatars/',
        default=get_default_avatar,
        verbose_name=_('Аватар'),
        validators=[
            FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg']),
            validate_size_image
        ],
        blank=True
    )
    phone = models.CharField(
        max_length=12, unique=True, verbose_name=_('Телефон')
    )
    email_ver = models.BooleanField(
        default=False, verbose_name=_('Электронная почта подтверждена')
    )
    slug = models.SlugField(
        max_length=255, unique=True, db_index=True, verbose_name='URL (slag)'
    )
    status = models.ForeignKey(
        to='app_marketplace.StatusModel',
        on_delete=models.CASCADE,
        verbose_name=_('Статус пользователя'),
        related_name='user',
        null=True
    )

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']
    email = models.EmailField(unique=True)

    def phone_number(self):
        return ' '.join(
            [
                '+7', f'({self.phone[0:3]})',
                f'{self.phone[3:6]}-{self.phone[6:8]}-{self.phone[8:10]}'
            ]
        )

    def get_absolute_url(self):
        return reverse('account', kwargs={'slug': self.slug})

djangoProject/app_users/views.py
import random
from django import views
from django.contrib.auth import authenticate, login
from django.db.models import Min, Max, IntegerField
from django.http import HttpResponseRedirect
from django.shortcuts import render
from app_users.forms import LoginForm, RegistrationForm, EditProfileForm
from app_users.models import User
from app_marketplace.services import (
    GetPurchaseHistoryService, AddLookedProductsService,
    GetDiscountsForProductsService, AddItemToCart
)
from app_marketplace.models import (
    ProductModel, CartProductModel, CartModel, OrderModel
)
from django.views.generic import DetailView, TemplateView, ListView
from app_marketplace.cart import Cart


class LoginView(views.View):
    """Представление авторизации пользователя."""
    @classmethod
    def get(cls, request, *args, **kwargs):
        form = LoginForm(request.POST or None)
        context = {
            'form': form
        }
        return render(request, 'app_users/login.html', context)

    @classmethod
    def post(cls, request, *args, **kwargs):
        form = LoginForm(request.POST or None)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(email=email, password=password)
            if user:
                login(request, user)
                cart_session = Cart(request)
                if cart_session.__len__() != 0:
                    for product in cart_session:
                        cart = CartModel.objects.filter(
                            user=user, status='actively').prefetch_related(
                            'products').first()
                        obj, created = \
                            CartProductModel.objects.update_or_create(
                                product=product['product'], user=user)
                        if created:
                            AddItemToCart().add_item_to_cart(
                                cart=cart,
                                product=obj,
                                amount=product['quantity'],
                                price=product['product'].price * product[
                                    'quantity']
                            )

                        else:
                            AddItemToCart().change_item_count_cart(
                                request=request,
                                product=obj.product,
                                count=product['quantity']
                            )

                        cart_session.delete(product['product'])

                return HttpResponseRedirect('/')
        context = {
            'form': form
        }
        return render(request, 'app_users/login.html', context, status=401)


class RegistrationView(views.View):
    """Регистрация пользователя."""
    template_name = 'app_users/registration.html'
    success_url = '/'

    @classmethod
    def get(cls, request, *args, **kwargs):
        form = RegistrationForm(request.POST or None)
        context = {
            'form': form
        }
        return render(request, cls.template_name, context)

    @classmethod
    def post(cls, request, *args, **kwargs):
        form = RegistrationForm(request.POST or None)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.email = form.cleaned_data['email']
            new_user.first_name = form.cleaned_data['first_name']
            new_user.last_name = form.cleaned_data['last_name']
            new_user.set_password(form.cleaned_data['password'])
            new_user.username = new_user.email.split('@')[0] + str(
                random.randint(1, 900000))
            new_user.slug = new_user.username
            new_user.save()
            user = authenticate(
                email=form.cleaned_data['email'],
                password=form.cleaned_data['password']
            )
            user.save()
            login(request, user)
            return HttpResponseRedirect(cls.success_url)
        context = {
            'form': form
        }
        return render(request, cls.template_name, context, status=400)


class AccountView(DetailView):
    """Страница аккаунта."""
    model = User
    template_name = 'app_users/account.html'
    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        order_history = GetPurchaseHistoryService().get_orders_history(
            user=self.object)
        if len(order_history) > 0:
            context['order_history'] =\
                GetPurchaseHistoryService().get_orders_history(
                    user=self.object)[0]
        else:
            context['order_history'] = None

        looked_history =\
            AddLookedProductsService().get_a_list_of_viewed_products(
                user=self.object, quantity=3
            )
        products_list = [product.product.id for product in looked_history]

        products_on_shops = ProductModel.objects.select_related().annotate(
            min_price=Min(
                'product_on_shop__price', output_field=IntegerField()
            ),
            max_price=Max(
                'product_on_shop__price', output_field=IntegerField())
        ).filter(id__in=products_list)

        if len(products_on_shops):
            product_on_shops = [
                (GetDiscountsForProductsService.get_discount_price(
                    product=product, price=product.min_price)[0]
                 if product.discounts.exists() else product.min_price, product)
                for product in products_on_shops
            ]

            context['products'] = product_on_shops
        return context


class ProfileView(views.View):
    """Обновление аккаунта."""
    @classmethod
    def get(cls, request, *args, **kwargs):
        return render(request, 'app_users/profile.html')

    @classmethod
    def post(cls, request, *args, **kwargs):
        form = EditProfileForm(
            request.POST, request.FILES, instance=request.user
        )
        if form.is_valid():
            fio = form.cleaned_data['fio'].split()
            if len(fio) == 1:
                first_name, last_name = fio[0], ''
            else:
                first_name, last_name = fio[0], fio[1]
            new_user = User.objects.get(**kwargs)
            new_user.first_name = first_name
            new_user.last_name = last_name
            new_user.avatar = form.cleaned_data['avatar']
            new_user.phone = form.cleaned_data['phone']
            new_user.email = form.cleaned_data['email']
            new_user.save()
            if form.cleaned_data['password'] != '':
                new_user.set_password(form.cleaned_data['password'])
                new_user.save()
                user = authenticate(
                    email=form.cleaned_data['email'],
                    password=form.cleaned_data['password']
                )
                login(request, user)

        context = {'errors': form.errors.get_json_data()}
        return render(request, 'app_users/profile.html', context)


class ProductHistoryView(TemplateView):
    """История просмотров пользователя."""
    template_name = 'app_users/view_history_products.html'

    def get_context_data(self, **kwargs):
        context = super(ProductHistoryView, self).get_context_data(**kwargs)
        product_list =\
            AddLookedProductsService().get_a_list_of_viewed_products(
                self.request.user)

        products_list = [product.product.id for product in product_list]

        products_on_shops = ProductModel.objects.select_related().annotate(
            min_price=Min(
                'product_on_shop__price', output_field=IntegerField()
            ),
            max_price=Max(
                'product_on_shop__price', output_field=IntegerField())
        ).filter(id__in=products_list)

        if len(products_on_shops):
            product_on_shops = [
                (GetDiscountsForProductsService.get_discount_price(
                    product=product, price=product.min_price)[0]
                 if product.discounts.exists() else product.min_price, product)
                for product in products_on_shops
            ]

            context['products'] = product_on_shops

        return context


class OrderHistoryView(ListView):
    """История заказов пользователя."""
    model = OrderModel
    template_name = 'app_users/order_history_list.html'
    context_object_name = 'order_list'

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(cart__user=self.request.user)


class OrderUserDetailView(DetailView):
    model = OrderModel
    template_name = 'app_users/user_order_detail.html'
    context_object_name = 'order'

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(cart__user=self.request.user)

djangoProject/templates/app_users/account.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
{% load static %}
<div class="Middle Middle_top">
    <div class="Middle-top">
        <div class="wrap">
            <div class="Middle-header">
                <h1 class="Middle-title">{% trans "Личный кабинет" %}
                </h1>
                <ul class="breadcrumbs Middle-breadcrumbs">
                    <li class="breadcrumbs-item"><a href="/">{% trans "Главная" %}</a>
                    </li>
                    <li class="breadcrumbs-item breadcrumbs-item_current"><span>{% trans "Личный кабинет" %}</span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="Section Section_column Section_columnLeft">
        <div class="wrap">
            <div class="Section-column">
                <div class="Section-columnSection">
                    <header class="Section-header">
                        <strong class="Section-title">{% trans "Меню" %}
                        </strong>
                    </header>
                    <div class="Section-columnContent">
                        <div class="NavigateProfile">
                            <ul class="menu menu_vt">
                                <li class="menu-item_ACTIVE menu-item"><a class="menu-link"
                                                                          href="{% url 'account' slug=user.slug %}">{% trans "Личный кабинет" %}</a>
                                </li>
                                <li class="menu-item"><a class="menu-link"
                                                         href="{% url 'account_update' slug=user.slug %}">{% trans "Профиль" %}</a>
                                </li>
                                <li class="menu-item"><a class="menu-link"
                                                         href="{% url 'history_orders' slug=request.user.slug %}">{% trans "История заказов" %}</a>
                                </li>
                                <li class="menu-item">
                                    <a class="menu-link" href="{% url 'history_products' slug=request.user.slug %}">
                                        {% trans "История просмотров" %}
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="Section-content">
                <div class="Account">
                    <div class="Account-group">
                        <div class="Account-column">
                            <div class="Account-avatar"><img
                                    src="/media/{{user.avatar}}"
                                    alt="{{user.avatar}}"/>
                            </div>
                        </div>
                        <div class="Account-column">
                            <div class="Account-name">{{ user.first_name }} {{user.last_name}}
                            </div>
                            <a class="Account-editLink" href="{% url 'account_update' slug=user.slug %}">{% trans "Редактировать профиль" %}</a>
                        </div>
                    </div>
                    <div class="Account-group">
                        <div class="Account-column Account-column_full">
                            <div class="Order Order_anons">
                                <div class="Order-personal">
                                    {%if order_history%}
                                    <div class="row">
                                        <div class="row-block"><a class="Order-title"
                                                                  href="#">{% trans "Заказ" %}&#32;<span
                                                class="Order-numberOrder">№{{order_history.id}}</span>&#32;от&#32;<span
                                                class="Order-dateOrder">{{order_history.date_order}}</span></a>
                                            <div class="Account-editLink"><a
                                                    href="#">{% trans "История заказов" %}</a>
                                            </div>
                                        </div>
                                        <div class="row-block">
                                            <div class="Order-info Order-info_delivery">
                                                <div class="Order-infoType">{% trans "Тип доставки" %}:
                                                </div>
                                                <div class="Order-infoContent">{{order_history.delivery_for_order.get_delivery_display}}
                                                </div>
                                            </div>
                                            <div class="Order-info Order-info_pay">
                                                <div class="Order-infoType">{% trans "Оплата" %}:
                                                </div>
                                                <div class="Order-infoContent">{{ order_history.get_payment_type_display }}
                                                </div>
                                            </div>
                                            <div class="Order-info">
                                                <div class="Order-infoType">{% trans "Итого" %}:
                                                </div>
                                                <div class="Order-infoContent">{{order_history.cart.total_price}}{% trans "руб" %}.
                                                </div>
                                            </div>
                                            <div class="Order-info Order-info_status">
                                                <div class="Order-infoType">{% trans "Статус" %}:
                                                </div>
                                                <div class="Order-infoContent">{{ order_history.get_status_display }}</div>
                                            </div>
                                        </div>
                                    
                                    </div>
                                    {%endif%}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="Account-group">
                        <div class="Account-column Account-column_full">
                            <header class="Section-header">
                                <h2 class="Section-title">{% trans "История просмотров" %}
                                </h2>
                            </header>
                            <div class="Cards Cards_account">
                                {% for product in products %}
                                {% if forloop.counter == 1 %}
                                <div class="Card">
                                    <a class="Card-picture" href="{% url 'good_details' slug=product.1.slug %}"><img
                                        src="{{product.1.main_image.file.url}}"
                                        alt="{{product.1.main_image.filename}}"/></a>
                                    {% elif forloop.counter == 2 %}
                                    <div class="Card hide_700">
                                        <a class="Card-picture" href="{% url 'good_details' slug=product.1.slug %}"><img
                                            src="{{product.1.main_image.file.url}}"
                                            alt="{{product.1.main_image.filename}}"/></a>
                                        {% else %}
                                        <div class="Card hide_md">
                                            <a class="Card-picture" href="{% url 'good_details' slug=product.1.slug %}"><img
                                                src="{{product.1.main_image.file.url}}"
                                                alt="{{product.1.main_image.filename}}"/></a>
                                            {%endif%}
                                            <div class="Card-content">
                                                <strong class="Card-title">
                                                    <a href="{% url 'good_details' slug=product.1.slug %}">{{product.1.model}}</a>
                                                </strong>
                                                <div class="Card-description">
                                                    <div class="Card-cost">
                                                        {% if product.0 != product.1.min_price %}
                                                        <span class="Card-priceOld">{{product.1.min_price}}</span>
                                                        {% endif %}
                                                        <span class="Card-price">{{product.0}}</span>
                                                    </div>
                                                    <div class="Card-category">{{product.1.category.name}}
                                                    </div>
                                                    <div class="Card-hover"><a class="Card-btn" href="{% url 'good_details' slug=product.1.slug %}">
                                                        <img src="{% static 'img/icons/card/bookmark.svg' %}"
                                                            alt="bookmark.svg"/></a><a class="Card-btn" href="#"><img
                                                            src="{% static 'img/icons/card/cart.svg' %}"
                                                            alt="cart.svg"/></a><a class="Card-btn" href="#"><img
                                                            src="{% static 'img/icons/card/change.svg' %}"
                                                            alt="change.svg"/></a>
                                                    </div>
                                                </div>
                                            </div>
                                             {% if product.0 != product.1.min_price %}
                                            <div class="Card-sale">{% trans "Скидка" %}</div>
                                            {% endif %}
                                        </div>
                                        {% endfor %}
                                    </div>

                                    <div class="Account-editLink Account-editLink_view">
                                        <a href="{% url 'history_products' slug=request.user.slug %}">{% trans "Полный список" %}</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

djangoProject/templates/app_users/order_history_list.html
{% load i18n %}
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <title>{% trans "История заказов" %}</title>
    {% include 'include/head.html' %}
</head>
<body class="Site">
  {% include 'include/header.html' %}

  <div class="Middle Middle_top">
    <div class="Middle-top">
      <div class="wrap">
        <div class="Middle-header">
          <h1 class="Middle-title">{% trans "История заказов" %}
          </h1>
          <ul class="breadcrumbs Middle-breadcrumbs">
            <li class="breadcrumbs-item"><a href="{% url 'main' %}">{% trans "Главная" %}</a>
            </li>
            <li class="breadcrumbs-item breadcrumbs-item_current"><span>{% trans "История заказов" %}</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="Section Section_column Section_columnLeft">
      <div class="wrap">
        <div class="Section-column">
          <div class="Section-columnSection">
            <header class="Section-header">
              <strong class="Section-title">{% trans "Меню" %}
              </strong>
            </header>
            <div class="Section-columnContent">
              <div class="NavigateProfile">
                <ul class="menu menu_vt">
                  <li class="menu-item">
                      <a class="menu-link" href="{% url 'account' slug=request.user.slug %}">{% trans "Личный кабинет" %}</a>
                  </li>
                  <li class="menu-item">
                      <a class="menu-link" href="{% url 'account_update' slug=request.user.slug %}">{% trans "Профиль" %}</a>
                  </li>
                  <li class="menu-item_ACTIVE menu-item">
                      <a class="menu-link" href="{% url 'history_orders' slug=request.user.slug %}">{% trans "История заказов" %}</a>
                  </li>
                  <li class="menu-item">
                      <a class="menu-link" href="{% url 'history_products' slug=request.user.slug %}">{% trans "История просмотров" %}</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="Section-content">
          <div class="Orders">
              {% for order in order_list %}
            <div class="Order Order_anons">
              <div class="Order-personal">
                <div class="row">
                  <div class="row-block">
                      <a class="Order-title" href="{% url 'user_order_detail' slug=request.user.slug pk=order.id %}">{% trans "Заказ" %}&#32;
                          <span class="Order-numberOrder">{{order.id}}</span>&#32;{% trans "от" %}&#32;
                          <span class="Order-dateOrder">{{ order.date_order }}</span>
                      </a>
                  </div>
                  <div class="row-block">
                    <div class="Order-info Order-info_delivery">
                      <div class="Order-infoType">{% trans "Тип доставки" %}:
                      </div>
                      <div class="Order-infoContent">{{ order.delivery_for_order.get_delivery_display }}
                      </div>
                    </div>
                    <div class="Order-info Order-info_pay">
                      <div class="Order-infoType">{% trans "оплата" %}:
                      </div>
                      <div class="Order-infoContent">{{ order.get_payment_type_display }}
                      </div>
                    </div>
                    <div class="Order-info">
                      <div class="Order-infoType">{% trans "Итого" %}:
                      </div>
                      <div class="Order-infoContent">
                          <span class="Order-price">{{ order.cart.total_price}}</span>
                      </div>
                    </div>
                    <div class="Order-info Order-info_status">
                      <div class="Order-infoType">{% trans "Статус" %}:
                      </div>
                      <div class="Order-infoContent">{{ order.get_status_display }}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
              {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% include 'include/footer.html' %}
</body>
</html>

djangoProject/templates/app_users/password_change_done.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}

<div class="container">
	<div class="d-flex flex-column">
		<h1 class="password-changed">{% trans "Пароль успешно обновлен" %}.</h1>
	</div>
</div>

{% endblock %}

djangoProject/templates/app_users/password_reset_form.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}

<div class="row" style="margin-bottom: 200px; margin-top: 100px;">
        <div class="col-md-6 offset-md-3">
            <h3 class="text-center">{% trans "Смена пароля" %}</h3>
			<form method="POST" class="login form-reset-password">
				{% csrf_token %}
				<label>email</label>
				<input name="email" class="form-control" type="email" id="id_email" required="true">
				<button class="btn login-btn" type="submit">{% trans "Изменить пароль" %}</button>
			</form>
		</div>
</div>




{% endblock %}

djangoProject/templates/app_users/registration.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}
<html lang="en">
<head>
    <title>{{category.name}}</title>
    {% include 'include/head.html' %}
</head>
<body class="Site">
{% include 'include/header.html' %}
    <div class="row" style="margin-bottom: 200px; margin-top: 100px;">
        <div class="col-md-6 offset-md-3">
            <h3 class="text-center">{% trans "Регистрация" %}</h3>
            <hr>
            {% if user.is_authenticated %}
            <p> Вы уже авторизованы </p>
            {% else %}
            <form class="login registration-form" action="{% url 'registration' %}" method="POST" style="background-color: transparent; color: #1b1b1b">
                {% csrf_token %}
                {{ form.as_p }}
                <input class="btn login-btn" type="submit" value="{% trans "Зарегистрироваться" %}">
            </form>
            {% endif %}
        </div>

    </div>
{% include 'include/footer.html' %}
<script>
$('#id_phone').mask('+7 (999) 999-99-99');
</script>
</body>
</html>